name: Test and Validate

on:
  push:
    branches: [main, master]
    paths-ignore:
      - '.github/workflows/sync-docs.yml'
      - 'README.md'
      - 'IMPROVEMENTS.md'
  
  pull_request:
    branches: [main, master]
    paths-ignore:
      - '.github/workflows/sync-docs.yml'
      - 'README.md'
      - 'IMPROVEMENTS.md'
  
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Check Node.js version
        run: |
          node --version
          npm --version
          echo "✅ Node.js environment ready"

      - name: Validate package.json
        run: |
          if [ ! -f "package.json" ]; then
            echo "❌ package.json not found"
            exit 1
          fi
          
          # Check if vitepress is in dependencies
          if ! npm list vitepress > /dev/null 2>&1; then
            echo "❌ VitePress not found in dependencies"
            exit 1
          fi
          
          echo "✅ package.json is valid"

      - name: Install dependencies
        run: |
          npm ci
          echo "✅ Dependencies installed successfully"

      - name: Check VitePress configuration
        run: |
          if [ ! -f ".vitepress/config.js" ]; then
            echo "❌ VitePress config not found"
            exit 1
          fi
          
          npx vitepress --version
          echo "✅ VitePress configuration is valid"

      - name: Validate documentation structure
        run: |
          if [ ! -d "docs" ]; then
            echo "❌ docs directory not found"
            exit 1
          fi
          
          if [ ! -f "index.md" ]; then
            echo "❌ index.md not found"
            exit 1
          fi
          
          echo "✅ Documentation structure is valid"
          
          # Count markdown files
          MD_COUNT=$(find . -name "*.md" | wc -l)
          echo "📄 Found $MD_COUNT markdown files"

      - name: Test build process
        run: |
          echo "🔨 Testing build process..."
          npm run build
          
          if [ ! -d ".vitepress/dist" ]; then
            echo "❌ Build failed: .vitepress/dist not found"
            exit 1
          fi
          
          if [ ! "$(ls -A .vitepress/dist)" ]; then
            echo "❌ Build failed: .vitepress/dist is empty"
            exit 1
          fi
          
          BUILD_SIZE=$(du -sh .vitepress/dist | cut -f1)
          echo "✅ Build successful! Size: $BUILD_SIZE"

      - name: Check for broken links
        run: |
          echo "🔗 Checking for broken links..."
          
          # Find all markdown files
          find . -name "*.md" -exec grep -l "\[.*\](" {} \; | while read file; do
            echo "Checking links in: $file"
            # Extract links and check if they're valid
            grep -o '\[.*\]([^)]*)' "$file" | sed 's/.*(\([^)]*\)).*/\1/' | while read link; do
              if [[ $link == http* ]]; then
                echo "  External link: $link"
              elif [[ $link == \#* ]]; then
                echo "  Anchor link: $link"
              else
                echo "  Internal link: $link"
                # Check if file exists
                if [[ $link == /* ]]; then
                  link=".$link"
                fi
                if [ ! -f "$link" ] && [ ! -f "${link}.md" ]; then
                  echo "    ⚠️  Warning: Link may be broken: $link"
                fi
              fi
            done
          done
          
          echo "✅ Link validation completed"

      - name: Validate components
        run: |
          echo "🧩 Validating custom components..."
          
          if [ -d ".vitepress/theme/components" ]; then
            echo "✅ Components directory found"
            ls -la .vitepress/theme/components/
          else
            echo "ℹ️ No custom components found"
          fi

      - name: Check for syntax errors
        run: |
          echo "🔍 Checking for syntax errors..."
          
          # Check JavaScript files
          find . -name "*.js" -not -path "./node_modules/*" -not -path "./.git/*" | while read file; do
            echo "Checking: $file"
            node -c "$file" || echo "  ❌ Syntax error in $file"
          done
          
          # Check Vue files (basic check)
          find . -name "*.vue" -not -path "./node_modules/*" -not -path "./.git/*" | while read file; do
            echo "Checking Vue file: $file"
            if ! grep -q "<template>" "$file" && ! grep -q "<script>" "$file"; then
              echo "  ⚠️  Warning: $file may not be a valid Vue component"
            fi
          done
          
          echo "✅ Syntax validation completed"

      - name: Performance check
        run: |
          echo "⚡ Performance check..."
          
          # Check build size
          BUILD_SIZE=$(du -sh .vitepress/dist | cut -f1)
          echo "Build size: $BUILD_SIZE"
          
          # Check number of files
          FILE_COUNT=$(find .vitepress/dist -type f | wc -l)
          echo "Number of files: $FILE_COUNT"
          
          # Check for large files
          find .vitepress/dist -type f -size +1M | while read file; do
            echo "⚠️  Large file detected: $file ($(du -h "$file" | cut -f1))"
          done
          
          echo "✅ Performance check completed"

      - name: Success summary
        run: |
          echo "🎉 All validations passed!"
          echo "✅ Build process is working correctly"
          echo "✅ Documentation structure is valid"
          echo "✅ No critical issues found"
          echo "📅 Validation completed at: $(date)"